### ISSUE TITLE
構築2024

### ISSUE THREAD

**Issue by kesompochy** [cto-a/private-isu-ops#54]
2024年も同じことをやるので構築していく

**Comment by kesompochy** [comment]
とりあえず前年と同様のものが動かせるようにしておきたい。何が必要だろうか。

- [ ] マシンを立ち上げて鍵と接続情報を配布できるようにする https://github.com/cto-a/private-isu-ops/issues/7
- [ ] ベンチマーカーが動くようにする https://github.com/cto-a/private-isu-ops/issues/3
- [ ] ポータルが表示できるようにする（ぜんぶtf化してたはず） https://github.com/cto-a/private-isu-ops/issues/1

**Comment by kesompochy** [comment]
とりあえず私が覚えていそうなポータルから作っていくか

**Comment by kesompochy** [comment]
ポータル一式が立ったはず。運用スクリプトに環境変数がハードコードされててつらい

**Comment by kesompochy** [comment]
initializeスクリプトを走らせて、ログインできることを確認した。
<img width="1630" alt="image" src="https://github.com/user-attachments/assets/ad82c7ed-98c4-41b8-850e-bc3961e97140">

ワークフローでOIDCで権限を得られないので手元で走らせた

**Comment by kesompochy** [comment]
競技サーバー

https://github.com/cto-a/private-isu-ops/issues/7#issuecomment-1596124400

どうやらマシンイメージはcatatsuyさんのものがあるらしい

**Comment by kesompochy** [comment]
lambda部分

https://github.com/cto-a/private-isu-ops/issues/8
https://github.com/cto-a/private-isu-ops/pull/32

- HTTPリクエストから送信もとIPを取得
- SQSに積む
- ECSタスクを起動する

以上の作業を実行するtsスクリプトがある。lambdaデプロイは手動でやってたという理解

**Comment by kesompochy** [comment]
ECS周りで何が行われていたかを見ている。SQS、tfコード化されてない気配がする。

**Comment by kesompochy** [comment]
ECS付近は @harukin721 がやりそう https://github.com/cto-a/private-isu-ops/pull/55 なのでそれ以外を進めていく。
とりあえずlambdaかな。なんらかのURLにcurlして関数が実行されるようにする。

**Comment by kesompochy** [comment]
https://github.com/cto-a/private-isu-ops/pull/59

```
$ curl https://8ukqooeebg.execute-api.ap-northeast-1.amazonaws.com
null⏎                                                                                      
```

わからないけどエンドポイントを叩いてnullが帰ってくるようになった

**Comment by kesompochy** [comment]
いまnullなのは単にエラーになっているだけっぽい。

```
2024-07-29T15:44:35.406Z	c9dd2a98-60d5-4185-b46f-589e8842daf2	ERROR	TypeError: Failed to parse URL from undefined
    at node:internal/deps/undici/undici:12502:13
    at async ije (file:///var/task/index.mjs:27:240851)
    at async Runtime.w$e [as handler] (file:///var/task/index.mjs:27:241571) {
  [cause]: TypeError: Invalid URL
      at new URL (node:internal/url:797:36)
      at new Request (node:internal/deps/undici/undici:4853:25)
      at fetch (node:internal/deps/undici/undici:9662:25)
      at fetch (node:internal/deps/undici/undici:12500:10)
      at value (node:internal/bootstrap/web/exposed-window-or-worker:72:12)
      at ije (file:///var/task/index.mjs:27:240857)
      at Runtime.w$e [as handler] (file:///var/task/index.mjs:27:241577)
      at Runtime.handleOnceNonStreaming (file:///var/runtime/index.mjs:1173:29) {
    code: 'ERR_INVALID_URL',
    input: 'undefined'
  }
}
```

環境変数の指定が足りないだけなのであとで調整する。

**Comment by kesompochy** [comment]
さて、SQSキューでも作るかな

**Comment by kesompochy** [comment]
https://github.com/cto-a/private-isu-ops/pull/60
雑に作った。あとはECSタスクが存在すると完全体になれる

**Comment by kesompochy** [comment]
残り

- [ ] ECSタスクが起動できるようになる
- [ ] 一通りができるようになる
  - [ ] インスタンスを立ち上げる
  - [ ] インスタンスにSSHできる
  - [ ] インスタンスからlambdaを起動できる
  - [ ] lambdaからベンチマーカーが走る
  - [ ] 得点が推移したことをポータルから確認できる
- [ ] 去年発覚したボトルネックを潰す
- [ ] 思いつくところをいい感じにする

**Comment by harukin721** [comment]
ECS タスクを起動しました。
https://github.com/cto-a/private-isu-ops/pull/55

---

```
# ECS ログ
exec /opt/go/run.sh: exec format error
```

ECR へのイメージプッシュでこれを引いたので見ています。
https://qiita.com/strings/items/ba4ab40b79b24ca4548d

**Comment by kesompochy** [comment]
```
exec format error
```

cpuアーキテクチャのやつでよく見るエラーだ

**Comment by harukin721** [comment]
colima 立ち上がってくれ..

```
% colima start --arch x86_64   
% docker build -t private-isu-benchmarker-repository --platform linux/x86_64 .
% docker tag private-isu-benchmarker-repository:latest 009160051284.dkr.ecr.ap-northeast-1.amazonaws.com/private-isu-benchmarker-repository:latest
% docker push 009160051284.dkr.ecr.ap-northeast-1.amazonaws.com/private-isu-benchmarker-repository:latest
```

**Comment by kesompochy** [comment]
適当なキーペアを作ってインスタンスを起動して次のことを確認できた

- 作った秘密鍵とubuntuユーザーでsshログインできる
- ラーメンのやつの画面が表示される

<img width="741" alt="image" src="https://github.com/user-attachments/assets/1fc1d6e4-6225-40d3-99f0-a8f0735fc24e">

設定は次のような感じ

- ami 
  - https://github.com/catatsuy/private-isu のx86_64
- スペック
  - c7a-large
- security group
  - 22, 80を全開放したやつを作った

**Comment by harukin721** [comment]
https://github.com/cto-a/private-isu-ops/issues/54#issuecomment-2257440114 いけたーー

**Comment by kesompochy** [comment]
やったぜ

**Comment by harukin721** [comment]
ログ変わった

<img width="1354" alt="image" src="https://github.com/user-attachments/assets/0b3382e9-5d4a-4110-940e-9e15b9f3435d">

https://ap-northeast-1.console.aws.amazon.com/ecs/v2/clusters/benchmarker-ecs-cluster/services/benchmark-ecs-service/logs?region=ap-northeast-1

**Comment by kesompochy** [comment]
https://github.com/cto-a/private-isu-ops/pull/62 インスタンスの起動がいい感じになったのでlambdaを叩いてSQSと接続、ECSタスクの起動ができるようにする

**Comment by kesompochy** [comment]
1.  インスタンス起動
2. ポータル用DB、ユーザーデータ初期化
3. インスタンスにSSHログイン
4. インスタンスからlambdaのURLを叩く
5. ポータルで得点推移が閲覧できる

以上の流れができるようになった。とりあえずこれで最低限の準備はOK？

<img width="1550" alt="image" src="https://github.com/user-attachments/assets/c72f706a-b9e2-4511-a555-1c6ce2925e47">

**Comment by yaggytter** [comment]
素晴らしい！！！
ちなみに、チームとIPが書いてあるスプレッドシートってどうしたんでしたっけ？

**Comment by kesompochy** [comment]
📝 昨年のものをそのまま使っているとdiscordで回答済み

このissueでやるべきことは終わったのでclose
